### PR TITLE
Extracted utils to separate package

### PR DESCRIPTION
**Pull request by crock**
Utils for the bot are now in this repo with a NPM package hosted on GitHub Package Registry.
https://github.com/crock/discord-bot-utils
https://github.com/crock/discord-bot-utils/packages/39768

### CODE REVIEW

**Comment by ap4gh** [comment]
I don't know about package registry on github yet. I recommend that the monolithic structure for bot is better than federated structure. What is the need for putting a part of bot(utils module) in a different place outside of the package itself?

**Comment by crock** [comment]
Our project is growing, so to keep thing maintainable, I only broke out the core utility classes. I can move it to the CodeCareer organization if you would prefer though.

**Comment by ap4gh** [comment]
Can we do without creating a registry for the `utils` module? Keeping everything in one place is neat and hassle free when it comes to developing. For example, FirebaseDB. Before firebase I used to fork the repo, do `npm install`, fill `config.json` file and start developing.

And now, I have to open GCP, move to the firebase app, forge through the docs because apparently I don't remember the APIs, ask for help and all this takes 30 mins. I don't know about Github registry but I do know, debugging development setup will take more time with it.

At the end, its your decision, I can approve the PR. But just saying, those you are providing free labor to the project should also have some peace of mind while working 😄.

**Comment by crock** [comment]
The GH package registry is just an npm registry. You can use npm install as normal and debug as normal. The only thing that changes is the imports now say

import { Auth } from '@crock/discord-bot-utils'

You should still get the linting. But I’ll keep the utilities in this repo for now.

**Comment by crock** [comment]
Decided not to implement this. Closing now. @ap4gh

**Pull request closed without merging**
